#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-.env.production}"
APP_NAME="${2:-textile-erp-api}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

required_vars=(
  DATABASE_URL
  APP_URL
  JWT_SECRET
  SUPER_ADMIN_EMAIL
  SUPER_ADMIN_PASSWORD
  SUPER_ADMIN_NAME
  CORS_ALLOWED_ORIGINS
  TRUST_PROXY
  LOG_LEVEL
  STORAGE_PROVIDER
  PRICING_GOOGLE_USD_RATE
)

for key in "${required_vars[@]}"; do
  if [[ -z "${!key:-}" ]]; then
    echo "Required variable is missing: $key" >&2
    exit 1
  fi
done

args=(
  set
  -a "$APP_NAME"
  "DATABASE_URL=$DATABASE_URL"
  "APP_URL=$APP_URL"
  "JWT_SECRET=$JWT_SECRET"
  "SUPER_ADMIN_EMAIL=$SUPER_ADMIN_EMAIL"
  "SUPER_ADMIN_PASSWORD=$SUPER_ADMIN_PASSWORD"
  "SUPER_ADMIN_NAME=$SUPER_ADMIN_NAME"
  "CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS"
  "TRUST_PROXY=$TRUST_PROXY"
  "LOG_LEVEL=$LOG_LEVEL"
  "STORAGE_PROVIDER=$STORAGE_PROVIDER"
  "UPLOADS_DIR=${UPLOADS_DIR:-uploads}"
  "UPLOADS_PUBLIC_BASE_URL=${UPLOADS_PUBLIC_BASE_URL:-}"
  "S3_ENDPOINT=${S3_ENDPOINT:-}"
  "S3_REGION=${S3_REGION:-auto}"
  "S3_BUCKET=${S3_BUCKET:-}"
  "S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-}"
  "S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-}"
  "S3_PUBLIC_BASE_URL=${S3_PUBLIC_BASE_URL:-}"
  "S3_FORCE_PATH_STYLE=${S3_FORCE_PATH_STYLE:-false}"
  "PRICING_GOOGLE_USD_RATE=$PRICING_GOOGLE_USD_RATE"
  "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}"
  "STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}"
  "STRIPE_PRICE_BASIC_MONTHLY=${STRIPE_PRICE_BASIC_MONTHLY:-}"
  "STRIPE_PRICE_BASIC_YEARLY=${STRIPE_PRICE_BASIC_YEARLY:-}"
  "STRIPE_PRICE_PRO_MONTHLY=${STRIPE_PRICE_PRO_MONTHLY:-}"
  "STRIPE_PRICE_PRO_YEARLY=${STRIPE_PRICE_PRO_YEARLY:-}"
  "BACKUP_KEEP_DAYS=${BACKUP_KEEP_DAYS:-7}"
  "BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}"
  "RUN_DB_BOOTSTRAP=false"
)

if [[ -n "${ALERT_WEBHOOK_URL:-}" ]]; then
  args+=("ALERT_WEBHOOK_URL=$ALERT_WEBHOOK_URL")
fi

exec fly secrets "${args[@]}"
